
stages:
  - build
  - publish


# Fedora 42 is used to ensure compatibility with the tools we need
Generate release notes on commit:
  stage: build
  image: fedora:42
  allow_failure: true
  script:
    - dnf install -q -y multimarkdown git-core libxslt
    - mkdir -p output
    - |-
      git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA | grep release-notes- | while read file; do echo Processing file $file; multimarkdown $file |  xsltproc  release-notes.xsl  - > output/$file.shtml; done
  artifacts:
    paths:
      - "output/*.shtml"

# Fedora 42 is used to ensure compatibility with the tools we need
# process version 9.x, 1x.x
Generate release notes:
  stage: build
  image: fedora:42
  when: manual
  script:
    - dnf install -q -y multimarkdown git-core libxslt
    - mkdir -p output
    - |-
      echo "Processing $file"
      for file in release-notes-{9,1?}.[0-9]; do echo Processing file $file; multimarkdown $file |  xsltproc  release-notes.xsl  - > output/$file.shtml; done
  artifacts:
    paths:
      - "output/*.shtml"

# Publish the release notes to the website
Publish release notes:
  stage: publish
  when: manual
  tags:
    - www.dcache.org
  script:
    - cp output/*.shtml /data/www/old-dcache.org/downloads/1.9/.